version: 2.1

jobs:
    build:
        docker:
            - image: cimg/rust:1.43.0

        environment:
            TZ: "/usr/share/zoneinfo/Europe/Kiev"

        steps:
            - checkout
            - restore_cache:
                  key: project-cache
            - run:
                  name: Check formatting
                  command: |
                      rustup component add rustfmt clippy
                      rustfmt --version
                      cargo clippy --all-targets --all-features -- -D warnings
                      cargo fmt -- --check
            - run:
                  name: Stable Build
                  command: |
                      rustup toolchain install stable
                      rustup run stable rustc --version --verbose
                      rustup run stable cargo --version --verbose
                      rustup run stable cargo build --verbose
            - run:
                  name: Test
                  command: rustup run stable cargo test
            - save_cache:
                  key: project-cache
                  paths:
                      - "~/.cargo"
                      - "./target"
