name: Rust

on:
    push:
        branches: [develop]
    pull_request:
        branches: [master]

env:
    CARGO_TERM_COLOR: always

jobs:
    build-and-deploy:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: cargo test --verbose
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1
            - name: Build, tag, and push image to Amazon ECR
              run: |
                  docker build -t pdf-generator:latest .
                  docker tag pdf-generator:latest 683720987193.dkr.ecr.us-east-2.amazonaws.com/pdf-generator:latest
                  docker push 683720987193.dkr.ecr.us-east-2.amazonaws.com/pdf-generator:latest

            - name: Logout of Amazon ECR
              if: always()
              run: docker logout ${{ steps.login-ecr.outputs.registry }}
